import './globals.css'
import { Open_Sans } from 'next/font/google';
import ReduxProvider from '@/redux/provider';

const open_sans = Open_Sans({
  subsets: ['latin'],
  weight: ['600', '700', '800']
})

export const metadata = {
  title: 'Live Chat',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
